services:
  devuntu:
    build: .
    image: devuntu:latest
    container_name: devuntu
    network_mode: host
    volumes:
      # ホストの ./home をコンテナの /home/ubuntu にマウント
      - ./home:/home/ubuntu
      # ホストの Docker 操作用
      - /var/run/docker.sock:/var/run/docker.sock
      # Windows の C ドライブをマウント (パス解決のため)
      - /mnt:/mnt
    privileged: true
    init: true
    stop_signal: SIGKILL
    stop_grace_period: 1s
    tty: true
    stdin_open: true
